@startuml clock_seq_push
title "【Clock】 シーケンス図（リファクタリング前）"

Clock -> Min : tick()

Min -> Min_ang : updateMin()

Min -> Hour : updateMin()
activate Hour
Hour -> Hour_ang : updateHour()
deactivate Hour

@enduml