@startuml
title "【Rendering MVC Pull】 シーケンス図"

Rendering ->  SpecularSurfaceColor : rendering()

activate SpecularSurfaceColor
SpecularSurfaceColor -> RightVector   : getValue()

activate RightVector
RightVector --> SpecularSurfaceColor
deactivate RightVector

SpecularSurfaceColor -> SurfaceNormal : getValue()
activate SurfaceNormal
SurfaceNormal --> SpecularSurfaceColor
deactivate SurfaceNormal

SpecularSurfaceColor -> SpecularColor : getValue()
activate SpecularColor
SpecularColor --> SpecularSurfaceColor
deactivate SpecularColor

SpecularSurfaceColor --> Rendering
deactivate SpecularSurfaceColor

@enduml