@startuml ssd_store_seq_pull_refactor_capacity
skinparam SequenceMessageAlignment center

-> ItemsByCapacity : getValue() : List<Map<String, Object>>
activate ItemsByCapacity

ItemsByCapacity -> Capacity : getValue() : int
activate Capacity
Capacity --> ItemsByCapacity : capacity
deactivate Capacity
ItemsByCapacity -> SiteWrapper : getSiteValue() : List<Map<String, Object>>
activate SiteWrapper
SiteWrapper -> SiteA : getValue() : ist<Map<String, Object>>
activate SiteA
SiteA --> SiteWrapper : siteA
deactivate SiteA
SiteWrapper --> ItemsByCapacity : siteValues
deactivate SiteWrapper
<-- ItemsByCapacity : value
deactivate ItemsByCapacity

@enduml