@startuml map_class_push_CFD
title "【仲介者オブジェクトの導入 実行後】"

together {
    class "A"{
        update(value: int): void
    }
    class "B"{
        updateA(a: int): void
    }
}

class "C"{
    updateB(b: int): void
}

class "D"<<Mediator>>{
    updateA(a: int): void
}

"A" o-up-> "1" "D"
"D" o-down-> "1" "B"
"B" o-right-> "1" "C"

@enduml