@startuml map_class_push_CFD
title "【仲介者オブジェクトの導入 実行後】"

class "A"{
    update(value: int):int
}
class "B"{
    update(value: int):void
}

class "C"<<Mediator>>{
    update(value: int):void
}

"C" <... "A" : value
"C" "1  " ---> "A" 
"C" ---> "1" "B"

@enduml