@startuml 【Audio】 Class-Diagram
title "【Audio】クラス図"

left to right direction

class AudioVolume{

}

class SoundVolume{

}

class BGMVolume{

}

class OutputSoundVolume{

}

class OutputBGMVolume{

}

AudioVolume <---o OutputBGMVolume
AudioVolume <---o OutputSoundVolume

SoundVolume <-right-o AudioVolume
BGMVolume <-left-o AudioVolume



'---------------------------------------------------------
@enduml