@startuml map_class_push_CFD
title "【仲介者オブジェクトへの依存 実行前】"
left to right direction

class "A"{
    getA():int
}
class "B"{
    calcB():int
}
class "C"{
    calcC(): int
}
class "D"<<Mediator>>{
    getA(): int
}

"A" "1"<--- "B" 
"A" ...> "B" : value
"A" ...> "D" : value
"A" "1" <--- "D"
"D" <--- "C"


@enduml