@startuml 【Clock】 Class-Diagram
title "【Clock】クラス図"

together {
    class "Hour"{
        -value : int
        +Hour()
        +getValue() : int
        +updateMin(min : int) : void
    }

    class "Min"{
        -hour : Hour
        -value : int
        +Min(hour: Hour, min_ang : Min_ang)
        +getValue() : int
        +tick() : void
    }
}

class "Min_ang"{
    -value : double
    +getValue() : double
    +updateMin(min : int) : double
}

class "Hour_ang"{
    -value : double
    +getValue() : double
    +updateHour(hour : int) : void
}

Min "1" o-down-> Hour : hour
Min "1" o-right-> Min_ang : min_ang
Hour "1" o-right-> Hour_ang : hour_ang


@enduml