@startuml clock_class_push_CFD
title "【Clock】クラス図（CFD適用後）"

left to right direction


class Hour_ang{
    -value : double
    +getValue() : double
    +updateHour(hour : int) : void
}

class Hour{
    -value : int
    +Hour()
    +getValue() : int
    +updateMin(min : int) : void
}

class Min_ang{
    -value : double
    +getValue() : double
    +updateMin(min : int) : double
}

class Min{
    -value : int
    +Min(hour: Hour)
    +getValue() : int
    +tick() : Map.Entry<Integer, Integer>
}

class Presenter{
    +Presenter(...)
    +tick() : void    
}

'---------------------------------------------------------
Presenter o--r-> "1  " Min : \nmin\n
Presenter o--d--> "1" Hour_ang : hour_ang
Presenter o--d--> "1" Min_ang : min_ang
Min o--r--> "1  " Hour : \nhour\n

@enduml