@startuml
title "CFD適用後 【Clock MVC Push】クラス図"

skinparam Linetype ortho

class Clock{
    -presenter : Presenter
    +Clock()
    +getHour_ang() : double
    +getHour() : int
    +getMin_ang() : double
    +getMin() : int
    +tick() : void
}

class Hour_ang{
    -value : double
    +getValue() : double
    +updateHour(hour : int) : void
}

class Hour{
    -value : int
    +Hour()
    +getValue() : int
    +updateMin(min : int) : void
}

class Min_ang{
    -value : double
    +getValue() : double
    +updateMin(min : int) : double
}

class Min{
    -hour : Hour
    -min_ang : Min_ang
    -value : int
    +Min(hour: Hour)
    +getValue() : int
    +tick() : Map.Entry<Integer, Integer>
}

class Presenter{
    +Presenter(...)
    +tick() : void    
}

'---------------------------------------------------------
Clock o--down-> Presenter

Presenter o-down-> Min
Presenter o-left-> Min_ang
Presenter o-right-> Hour_ang

Min o-down-> Hour

@enduml