@startuml
title "CFD適用後 【Clock MVC Push】クラス図"

class Hour_ang{
    -value : double
    +getValue() : double
    +updateHour(hour : int) : void
}

class Hour{
    -value : int
    +Hour()
    +getValue() : int
    +updateMin(min : int) : void
}

class Min_ang{
    -value : double
    +getValue() : double
    +updateMin(min : int) : double
}

class Min{
    -value : int
    +Min(hour: Hour)
    +getValue() : int
    +tick() : Map.Entry<Integer, Integer>
}

class Presenter{
    +Presenter(...)
    +tick() : void    
}

'---------------------------------------------------------
Presenter o-down-> "1" Min : min
Presenter o-left-> "1" Min_ang : min_ang
Presenter o-right-> "1" Hour_ang : hour_ang
Presenter o--down--> "1" Hour : hour

Min o-down-> "1" Hour : hour

@enduml