@startuml map_class_push
title "【Map】クラス図"

together {
    class "Longitude"{
        -value : double
        +Longitude(mapLongitude : MapLongitude)
        +getValue() : double
        +updateGPS(lat2 : double, long2 : double) : void
    }

    class "Latitude"{
        -value : double
        +Latitude(mapLatitude : MapLatitude)
        +getValue() : double
        +updateGPS(lat2 : double, long2 : double) : void
    }
}

class "MapLongitude"{
    -value : double
    +getValue() : double
    +updateLongitude(longitude : double) : void
}

class "MapLatitude"{
    -value : double
    +getValue() : double
    +updateLatitude(longitude : double) : void
}


Longitude  o--right-> "1 " MapLongitude : "  mapLongitude  "
Longitude  -[hidden]-     Latitude

Latitude   o--right-> "1 " MapLatitude : "  mapLatitude  "

@enduml