@startuml map_class_push_CFD
title "【Clock】クラス図"

together {
    class "Longitude"{
        -value : int
        +Hour()
        +getValue() : int
        +updateMin(min : int) : void
    }

    class "Latitude"{
        -value : int
        +Min(hour: Hour, min_ang : Min_ang)
        +getValue() : int
        +tick() : void
    }
}

class "MapLongitude"{
    -value : double
    +getValue() : double
    +updateMin(min : int) : double
}

class "MapLatitude"{
    -value : double
    +getValue() : double
    +updateHour(hour : int) : void
}


Longitude  o-right-> "1 " MapLatitude
Longitude  -[hidden]-     Latitude

Latitude   o-right-> "1 " MapLongitude

@enduml