@startuml
title "【Rendering MVC Pull】クラス図"

skinparam Linetype ortho

class Rendering{
}

class LightVector{
    - value : Vec3
    + LightVector()
    + getValue() : Vec3
}

class SurfaceNormal{
    - value : Vec3
    + SurfaceNormal()
    + getValue() : Vec3
}

class SpecularColor{
    - value : Color
    + SpecularColor() 
    + getValue() : Color
}

class DiffuseColor{
    - value : Color
    + DiffuseColor()
    + getValue() : Color
}

class SpecularSurfaceColor{
    + SpecularSurfaceColor()
}

class DiffuseSurfaceColor{
    + DiffuseSurfaceColor()
}


'---------------------------------------------------------
class Vec3{
    - x : double
    - y : double
    - z : double
    + Vec3()
    + getX() : double
    + getY() : double
    + getZ() : double
}

class Color{
    - r : int
    - g : int
    - b : int
    + Color()
    + getR() : int
    + getG() : int
    + getB() : int
}
'---------------------------------------------------------
@enduml