@startuml
title "Clock MVC Pushクラス図"

skinparam Linetype ortho

class Clock{
    -hour_ang : Hour_ang
    -hour : Hour
    -min_ang : Min_ang
    -min : Min
    +Clock()
    +getHour_ang() : double
    +getHour() : int
    +getMin_ang() : double
    +getMin() : int
    +tick() : void
}

class Hour_ang{
    -value : double
    +getValue() : double
    +updateHour(hour : int) : void
}

class Hour{
    -hour_ang : Hour_ang
    -value : int
    +Hour()
    +getValue() : int
    +updateMin(min : int) : void
}

class Min_ang{
    -value : double
    +getValue() : double
    +updateMin(min : int) : double
}

class Min{
    -hour : Hour
    -min_ang : Min_ang
    -value : int
    +Min(hour: Hour, min_ang : Min_ang)
    +getValue() : int
    +tick() : void
}

'---------------------------------------------------------
Clock o--left--> Min
Clock o--down--> Hour
Clock o--down-> Hour_ang
Clock o--down-> Min_ang

Min o-right-> Hour
Min o-down-> Min_ang

Hour o-down-> Hour_ang

@enduml